import type { Metadata } from "next";
import "./globals.css";
import MaxWidthWrapper from '@/lib/components/layout/max-width-wrapper'
import {Montserrat} from 'next/font/google'

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['500', '600', '700']
})

export const metadata: Metadata = {
  title: "Movie List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <main className="flex-grow">
          <MaxWidthWrapper>
            {children}
          </MaxWidthWrapper>
        </main>
      </body>
    </html>
  );
}
